name: Package Deployment
on:
  push:
    branches:
      - master
jobs:
  debbuild:
    name: Debian
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential gzip devscripts debhelper
      - name: Build Debian Package
        run: |
          bash ./configure.sh --deb buster
          debuild -i -us -uc -b
          mkdir -p ./pkgs
          mv ../wsl*.* ./pkgs
      - uses: actions/upload-artifact@v1
        with:
          name: DebianDEBs
          path: pkgs
  pgwbuild:
    name: Pengwin
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential gzip devscripts debhelper
      - name: Build Debian Package
        run: |
          bash ./configure.sh --deb bullseye
          debuild -i -us -uc -b
          mkdir -p ./pkgs
          mv ../wsl*.* ./pkgs
      - uses: actions/upload-artifact@v1
        with:
          name: PengwinDEBs
          path: pkgs
  pgwspdeploy:
    name: Pengwin Deploying
    needs: pgwbuild
    runs-on: ubuntu-18.04
    container: circleci/ruby:2.3-jessie
    steps:
      - name: Retrive package for deployment
        uses: actions/download-artifact@v1
        with:
          name: PengwinDEBs
      - run: gem install package_cloud
      - name: deploy to the dev
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PGW_DEV_DEPLOY_KEY }}
        run: package_cloud push whitewaterfoundry/wslu/debian/bullseye ./PengwinDEBs/*.deb --skip-errors
  rpmbuild:
    name: RPM
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq build-essential tar
      - name: 
        run: |
          bash ./configure.sh --rpm
          cp extras/build/rpm/wslu.spec ../wslu.spec
          rm -rf *
          mkdir -p SOURCES
          mkdir -p SPECS
          cp ../wslu-*.tar.gz SOURCES
          cp ../wslu.spec SPECS
      - name: rpmbuild
        uses: ./.github/actions/rpmbuild/
      - name: moving files
        run: |
          mkdir compiled_rpms
          cp SRPMS/* compiled_rpms
          cp RPMS/noarch/* compiled_rpms
        #uses: robertdebock/rpmbuild-action@1.1.1
      - uses: actions/upload-artifact@v1
        with:
          name: RPMs
          path: compiled_rpms
  coprdeploy:
    name: COPR Deploying
    needs: rpmbuild
    container: fedora:latest
    runs-on: ubuntu-latest
    steps:
        - name: Retrive package for deployment
          uses: actions/download-artifact@v1
          with:
            name: RPMs
        - name: Install API token for copr-cli
          env:
            API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
          run: |
            mkdir -p "$HOME/.config"
            echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"
        - name: Install tooling for source RPM build
          run: |
            dnf -y install @development-tools @rpm-development-tools
            dnf -y install copr-cli make
        - name: Submit the build by uploading the source RPM
          run: copr build praiskup/argparse-manpage-ci RPMs/*.src.rpm