name: General Tests
on: [push]
jobs:
  generaltests:
    name: General Tests
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          update: 'true'
          set-as-default: 'true'
          additional-packages:
            gzip
            make
            desktop-file-utils
            bats
      - shell: wsl-bash -u root {0}
        run: |
          make
          make install
          make test


